title: Printshop

markdown: GFM

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-default-layout

minima:
  skin: auto

  nav_pages:
    - printshop/index.md
    - slime/index.md
